In [53]:
import numpy as np
import pandas as pd

In [54]:
data = pd.read_csv("IMDB Dataset.csv")

In [55]:
data.head(6)

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive
5  Probably my all-time favorite movie, a story o...  positive

In [56]:
data.shape

(50000, 2)

In [57]:
data["sentiment"].value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

In [58]:
data.replace({"sentiment":{"positive":1,"negative":0}},inplace=True)

C:\Users\Anjali\AppData\Local\Temp\ipykernel_27832\3877186056.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data.replace({"sentiment":{"positive":1,"negative":0}},inplace=True)

In [59]:
data['sentiment']

0        1
1        1
2        1
3        0
4        1
        ..
49995    1
49996    0
49997    0
49998    0
49999    0
Name: sentiment, Length: 50000, dtype: int64

In [60]:
data

                                                  review  sentiment
0      One of the other reviewers has mentioned that ...          1
1      A wonderful little production. <br /><br />The...          1
2      I thought this was a wonderful way to spend ti...          1
3      Basically there's a family where a little boy ...          0
4      Petter Mattei's "Love in the Time of Money" is...          1
...                                                  ...        ...
49995  I thought this movie did a down right good job...          1
49996  Bad plot, bad dialogue, bad acting, idiotic di...          0
49997  I am a Catholic taught in parochial elementary...          0
49998  I'm going to have to disagree with the previou...          0
49999  No one expects the Star Trek movies to be high...          0

[50000 rows x 2 columns]

In [61]:
data['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

# 1. Remove HTML Tags

In [62]:
import re
def remove_html(text):
    pattern = re.compile("<.*?>")
    return pattern.sub(r'',text)

In [63]:
remove_html(data['review'][0])

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

In [64]:
# apply on whole review column

In [65]:
data['review']= data['review'].apply(remove_html)

In [66]:
data['review'][1]

'A wonderful little production. The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well done.'

In [67]:
# 2. lower case

In [68]:
data['review'].str.lower()

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. the filming tec...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

In [69]:
# LSTM

In [109]:
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, Input, LSTM
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [72]:
train_data, test_data = train_test_split(data, test_size = 0.2, random_state=42)

In [73]:
train_data.shape

(40000, 2)

In [75]:
test_data.shape

(10000, 2)

In [ ]:
# Text
#  ↓
# Tokenizer
#  ↓
# Sequences (numbers)
#  ↓
# Padding
#  ↓
# Deep Learning Model (LSTM)

In [87]:
# Tokenization 
# step1 

# tokenizer = Tokenizer(num_words=5000)
# tokenizer.fit_on_texts(train_data['review'])

# print(tokenizer.word_index)

# # step2 
# sequence = tokenizer.texts_to_sequences(train_data['review'])
# print(sequence)

# # step3 
# padded = pad_sequences(sequence, maxlen=200)
# print(padded)

In [90]:
# Tokenization
tokenizer = Tokenizer(num_words=5000)
tokenizer.fit_on_texts(train_data['review'])

In [91]:
# sequence and padding

X_train = pad_sequences(tokenizer.texts_to_sequences(train_data['review']),maxlen=200)
X_test = pad_sequences(tokenizer.texts_to_sequences(test_data['review']),maxlen=200)

In [92]:
X_train

array([[   1,  726, 1934, ...,  204,  350, 3851],
       [  60,   25, 2111, ...,   88,  102,    8],
       [   0,    0,    0, ...,    2,  708,   61],
       ...,
       [   0,    0,    0, ..., 1639,    2,  603],
       [   0,    0,    0, ...,  244,  102,  124],
       [   0,    0,    0, ...,   69,   72, 2060]], dtype=int32)

In [93]:
X_test

array([[   0,    0,    0, ...,  993,  722,  155],
       [   8,   57,   25, ...,   47,    9,  379],
       [   0,    0,    0, ...,   49, 1086,   96],
       ...,
       [   0,    0,    0, ...,  124,  199, 3249],
       [   0,    0,    0, ..., 1064,    1, 2304],
       [   0,    0,    0, ...,    1,  332,   26]], dtype=int32)

In [94]:
Y_train = train_data["sentiment"]
Y_test = test_data["sentiment"]

In [95]:
Y_train

39087    0
30893    0
45278    1
16398    0
13653    0
        ..
11284    1
44732    1
38158    0
860      1
15795    1
Name: sentiment, Length: 40000, dtype: int64

In [96]:
# LSTM MODEL BUILDING

In [110]:
model = Sequential([
    Input(shape=(200,)),
    Embedding(input_dim=5000,output_dim=128),
    LSTM(128,dropout=0.2,recurrent_dropout=0.2),
    Dense(1,activation='sigmoid')
])

In [111]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)              │ (None, 200, 128)            │         640,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_4 (LSTM)                        │ (None, 128)                 │         131,584 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 1)                   │             129 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 771,713 (2.94 MB)

 Trainable params: 771,713 (2.94 MB)

 Non-trainable params: 0 (0.00 B)

In [112]:
model.compile(optimizer = 'adam' ,loss = 'binary_crossentropy',metrics = ['accuracy'])

In [114]:
model.fit(X_train,Y_train, epochs=5, batch_size=64, validation_split=0.2)

Epoch 1/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 174s 340ms/step - accuracy: 0.7872 - loss: 0.4617 - val_accuracy: 0.8474 - val_loss: 0.3615
Epoch 2/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 150s 301ms/step - accuracy: 0.8472 - loss: 0.3630 - val_accuracy: 0.8577 - val_loss: 0.3384
Epoch 3/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 149s 298ms/step - accuracy: 0.8714 - loss: 0.3128 - val_accuracy: 0.8717 - val_loss: 0.3187
Epoch 4/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 136s 272ms/step - accuracy: 0.8869 - loss: 0.2800 - val_accuracy: 0.8731 - val_loss: 0.3312
Epoch 5/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 147s 294ms/step - accuracy: 0.9055 - loss: 0.2400 - val_accuracy: 0.8798 - val_loss: 0.3165

In [118]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [119]:
import joblib
joblib.dump(tokenizer,'tokenizer.pkl')

['tokenizer.pkl']

In [115]:
loss,accuracy = model.evaluate(X_test,Y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.8806 - loss: 0.2958

In [116]:
loss

0.2957741916179657

In [117]:
accuracy

0.8805999755859375

In [147]:
def predictive_system(review):

    # 1. Remove html tags.
    review = remove_html(review)

    # 2.lowercase
    review = review.lower()

    # 3.tokenization
    sequence = tokenizer.texts_to_sequences([review])

    # 4.Padding 
    padded_sequence = pad_sequences(sequence,maxlen =200)

    # 5.Prediction
    prediction = model.predict(padded_sequence)

    sentiment = "positive" if prediction[0][0] > 0.5 else "Negative"
    
    return sentiment

In [148]:
predictive_system("This movie was fantastic and amazing")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step

'positive'

In [149]:
predictive_system("A trilling adventure with stunning visual")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

'positive'

In [150]:
predictive_system("A visual masterpiece")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step

'positive'

In [152]:
predictive_system("Overall long and slow")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step

'Negative'

In [153]:
predictive_system('Overdramatic and boring')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

'Negative'

In [154]:
predictive_system('Bad experience')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

'Negative'